apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client
      app.kubernetes.io/version: "0.0.1"
      app.kubernetes.io/component: ui
      app.kubernetes.io/part-of: yolo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: yolo
    spec:
      containers:
      - name: client
        image: timaali/client:latest
        envFrom:
          - secretRef:
              name: client-secrets
        ports:
          - name: http
            containerPort: 80


---


