apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "mongodb-pvc"
  namespace: "yolo"
  labels: 
    app: "mongo-db"
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
  storageClassName: gp2